general:
  iface: "eth0"

  maps:
    path: /sys/fs/bpf/vanguard
    pin: false

  block_config:
    base_block_secs: 60
    max_block_secs: 604800
    rep_cooldown_secs: 1800

  grpc:
    up: true
    addr: "0.0.0.0:8080"

  accesslist:
    - addr: "1.2.3.4:4321"
      is_block: true
      until: 1234567890
    - addr: "5.6.7.8:1234"
      is_block: true
    - addr: "192.168.1.1:1234"
      is_block: false
      until: 1234567890
    - addr: "10.0.0.0:8080 /24"
      is_block: false

xdp:
  config:
    enable: true
    rate_limit: 1000
    burst_limit: 1000
    default_action: "pass"

  rules:
    - key: { addr: "5.6.7.8:80", eth: "ipv4", proto: "tcp" }
      value: { action: "drop" }

    - key: { addr: "[2001:db8::1]:443", eth: "ipv6", proto: "udp" }
      value: { action: "pass" }
    
    - key: { addr: "0.0.0.0:53", eth: "ipv4", proto: "tcp" }
      value:
        action: "tx"
        flag: 
        encap: "ip-in-ip"
        algo: "hash"
        to:
          - { addr: "1.1.1.1:443" }
          - { addr: "8.8.8.8:80" }
          - { addr: "77.88.8.8:8080" }

    - key: { addr:: "1.1.1.1:8000", eth: "ipv4", proto: "udp" }
      value:
        action: "redirect"
        to_iface: "docker"

tc:
  config:
    enable: true
    default_action: "pass"

  rules:
    - key: { direction: "egress", addr: "0.0.0.0:25", eth: "ipv4", proto: "tcp" }
      value: { action: "drop" }

    - key: { direction: "ingress", addr: "0.0.0.0:443", eth: "ipv4", proto: "tcp" }
      value: { action: "mirror", to_iface: "eth1" }

    - key: { direction: "ingress", addr: "0.0.0.0:8080", eth: "ipv4", proto: "tcp" }
      value:
        action: "redirect"
        algo: "round_robin"
        to:
          - { addr: "172.17.0.2:8080" }
          - { addr: "172.17.0.3:8080" }
          - { addr: "172.17.0.4:8080" }