[package]
name = "vanguard-cli"
version.workspace = true
edition.workspace = true

[dependencies]
vanguard-core = { path = "../vanguard-core", features = ["userspace"] }
vanguard-grpc = { path = "../vanguard-grpc" }
aya = { workspace = true }
clap = { workspace = true, features = ["derive"] }
tokio = { workspace = true }
erret-result = { workspace = true }

[features]
default = []