[package]
name = "vanguard-cli"
version.workspace = true
edition.workspace = true

[dependencies]
aya = { workspace = true }
clap = { workspace = true, features = ["derive"] }
vanguard-grpc = { path = "../vanguard-grpc" }
vanguard-common = { path = "../vanguard-common" }
tokio = { workspace = true }

[features]
default = []