[package]
name = "vanguard-grpc"
version.workspace = true
edition.workspace = true

[dependencies]
vanguard-common = { path = "../vanguard-common" }
aya = { workspace = true }
env_logger = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true }
tonic-prost = { workspace = true }
prost = { workspace = true }
network-types = { workspace = true }

[build-dependencies]
tonic-prost-build = "0.14.6"

[features]
default = []