use erret_result::*;

use crate::maps::*;

use network_types::{
    eth::EtherType,
    ip::IpProto,
};

use crate::error::VanguardError;

pub trait Parse: Sized {
    fn as_str(&self) -> String;
    fn to_type(s: String) -> ErrResult<Self>;
}

impl Parse for EtherType {
    fn as_str(&self) -> String {
        match self {
            Self::Ipv4 => "ipv4".to_string(),
            Self::Ipv6 => "ipv6".to_string(),
            Self::Arp => "arp".to_string(),
            Self::Loop => "loop".to_string(),
            Self::Ieee8021ad => "ieee8021ad".to_string(),
            Self::Ieee8021MacSec => "ieee8021macsec".to_string(),
            Self::Ieee8021ah => "ieee8021ah".to_string(),
            Self::Ieee8021mvrp => "ieee8021mvrp".to_string(),
            Self::FibreChannel => "fibrechannel".to_string(),
            Self::Infiniband => "infiniband".to_string(),
            Self::LoopbackIeee8023 => "loopbackieee8023".to_string(),
            Self::Ieee8021QinQ1 => "ieee8021qinq1".to_string(),
            Self::Ieee8021QinQ2 => "ieee8021qinq2".to_string(),
            Self::Ieee8021QinQ3 => "ieee8021qinq3".to_string(),
            Self::Ieee8021q => "ieee8021q".to_string(),
        }
    }

    fn to_type(s: String) -> ErrResult<Self> {
        match s.to_lowercase().trim() {
            "ipv4" => Ok(Self::Ipv4),
            "ipv6" => Ok(Self::Ipv6),
            "arp" => Ok(Self::Arp),
            "loop" => Ok(Self::Loop),
            "ieee8021ad" => Ok(Self::Ieee8021ad),
            "ieee8021macsec" => Ok(Self::Ieee8021MacSec),
            "ieee8021ah" => Ok(Self::Ieee8021ah),
            "ieee8021mvrp" => Ok(Self::Ieee8021mvrp),
            "fibrechannel" => Ok(Self::FibreChannel),
            "infiniband" => Ok(Self::Infiniband),
            "loopbackieee8023" => Ok(Self::LoopbackIeee8023),
            "ieee8021qinq1" => Ok(Self::Ieee8021QinQ1),
            "ieee8021qinq2" => Ok(Self::Ieee8021QinQ2),
            "ieee8021qinq3" => Ok(Self::Ieee8021QinQ3),
            _ => Err(VanguardError::Io("unknown ethertype").into()),
        }
    }
}

impl Parse for IpProto {
    fn as_str(&self) -> String {
        match self {
            Self::HopOpt => "hopopt".to_string(),
            Self::Icmp => "icmp".to_string(),
            Self::Igmp => "igmp".to_string(),
            Self::Ggp => "ggp".to_string(),
            Self::Ipv4 => "ipv4".to_string(),
            Self::Stream => "stream".to_string(),
            Self::Tcp => "tcp".to_string(),
            Self::Cbt => "cbt".to_string(),
            Self::Egp => "egp".to_string(),
            Self::Igp => "igp".to_string(),
            Self::BbnRccMon => "bbnrccmon".to_string(),
            Self::NvpII => "nvpii".to_string(),
            Self::Pup => "pup".to_string(),
            Self::Argus => "argus".to_string(),
            Self::Emcon => "emcon".to_string(),
            Self::Xnet => "xnet".to_string(),
            Self::Chaos => "chaos".to_string(),
            Self::Udp => "udp".to_string(),
            Self::Mux => "mux".to_string(),
            Self::DcnMeas => "dcnmeas".to_string(),
            Self::Hmp => "hmp".to_string(),
            Self::Prm => "prm".to_string(),
            Self::Idp => "idp".to_string(),
            Self::Trunk1 => "trunk1".to_string(),
            Self::Trunk2 => "trunk2".to_string(),
            Self::Leaf1 => "leaf1".to_string(),
            Self::Leaf2 => "leaf2".to_string(),
            Self::Rdp => "rdp".to_string(),
            Self::Irtp => "irtp".to_string(),
            Self::Tp4 => "tp4".to_string(),
            Self::Netblt => "netblt".to_string(),
            Self::MfeNsp => "mfensp".to_string(),
            Self::MeritInp => "meritinp".to_string(),
            Self::Dccp => "dccp".to_string(),
            Self::ThirdPartyConnect => "thirdpartyconnect".to_string(),
            Self::Idpr => "idpr".to_string(),
            Self::Xtp => "xtp".to_string(),
            Self::Ddp => "ddp".to_string(),
            Self::IdprCmtp => "idprcmtp".to_string(),
            Self::TpPlusPlus => "tpplusplus".to_string(),
            Self::Il => "il".to_string(),
            Self::Ipv6 => "ipv6".to_string(),
            Self::Sdrp => "sdrp".to_string(),
            Self::Ipv6Route => "ipv6route".to_string(),
            Self::Ipv6Frag => "ipv6frag".to_string(),
            Self::Idrp => "idrp".to_string(),
            Self::Rsvp => "rsvp".to_string(),
            Self::Gre => "gre".to_string(),
            Self::Dsr => "dsr".to_string(),
            Self::Bna => "bna".to_string(),
            Self::Esp => "esp".to_string(),
            Self::Ah => "ah".to_string(),
            Self::Inlsp => "inlsp".to_string(),
            Self::Swipe => "swipe".to_string(),
            Self::Narp => "narp".to_string(),
            Self::Mobile => "mobile".to_string(),
            Self::Tlsp => "tlsp".to_string(),
            Self::Skip => "skip".to_string(),
            Self::Ipv6Icmp => "ipv6icmp".to_string(),
            Self::Ipv6NoNxt => "ipv6nonxt".to_string(),
            Self::Ipv6Opts => "ipv6opts".to_string(),
            Self::AnyHostInternal => "anyhostinternal".to_string(),
            Self::Cftp => "cftp".to_string(),
            Self::AnyLocalNetwork => "anylocalnetwork".to_string(),
            Self::SatExpak => "satexpak".to_string(),
            Self::Kryptolan => "kryptolan".to_string(),
            Self::Rvd => "rvd".to_string(),
            Self::Ippc => "ippc".to_string(),
            Self::AnyDistributedFileSystem => "anydistributedfilesystem".to_string(),
            Self::SatMon => "satmon".to_string(),
            Self::Visa => "visa".to_string(),
            Self::Ipcv => "ipcv".to_string(),
            Self::Cpnx => "cpnx".to_string(),
            Self::Cphb => "cphb".to_string(),
            Self::Wsn => "wsn".to_string(),
            Self::Pvp => "pvp".to_string(),
            Self::BrSatMon => "brsatmon".to_string(),
            Self::SunNd => "sunnd".to_string(),
            Self::WbMon => "wbmon".to_string(),
            Self::WbExpak => "wbexpak".to_string(),
            Self::IsoIp => "isoip".to_string(),
            Self::Vmtp => "vmtp".to_string(),
            Self::SecureVmtp => "securevmtp".to_string(),
            Self::Vines => "vines".to_string(),
            Self::Ttp => "ttp".to_string(),
            Self::NsfnetIgp => "nsfnetigp".to_string(),
            Self::Dgp => "dgp".to_string(),
            Self::Tcf => "tcf".to_string(),
            Self::Eigrp => "eigrp".to_string(),
            Self::Ospfigp => "ospfigp".to_string(),
            Self::SpriteRpc => "spriterpc".to_string(),
            Self::Larp => "larp".to_string(),
            Self::Mtp => "mtp".to_string(),
            Self::Ax25 => "ax25".to_string(),
            Self::Ipip => "ipip".to_string(),
            Self::Micp => "micp".to_string(),
            Self::SccSp => "sccsp".to_string(),
            Self::Etherip => "etherip".to_string(),
            Self::Encap => "encap".to_string(),
            Self::AnyPrivateEncryptionScheme => "anyprivateencryptionscheme".to_string(),
            Self::Gmtp => "gmtp".to_string(),
            Self::Ifmp => "ifmp".to_string(),
            Self::Pnni => "pnni".to_string(),
            Self::Pim => "pim".to_string(),
            Self::Aris => "aris".to_string(),
            Self::Scps => "scps".to_string(),
            Self::Qnx => "qnx".to_string(),
            Self::ActiveNetworks => "activenetworks".to_string(),
            Self::IpComp => "ipcomp".to_string(),
            Self::Snp => "snp".to_string(),
            Self::CompaqPeer => "compaqpeer".to_string(),
            Self::IpxInIp => "ipxinip".to_string(),
            Self::Vrrp => "vrrp".to_string(),
            Self::Pgm => "pgm".to_string(),
            Self::AnyZeroHopProtocol => "anyzerohopprotocol".to_string(),
            Self::L2tp => "l2tp".to_string(),
            Self::Ddx => "ddx".to_string(),
            Self::Iatp => "iatp".to_string(),
            Self::Stp => "stp".to_string(),
            Self::Srp => "srp".to_string(),
            Self::Uti => "uti".to_string(),
            Self::Smp => "smp".to_string(),
            Self::Sm => "sm".to_string(),
            Self::Ptp => "ptp".to_string(),
            Self::IsisOverIpv4 => "isisoveripv4".to_string(),
            Self::Fire => "fire".to_string(),
            Self::Crtp => "crtp".to_string(),
            Self::Crudp => "crudp".to_string(),
            Self::Sscopmce => "sscopmce".to_string(),
            Self::Iplt => "iplt".to_string(),
            Self::Sps => "sps".to_string(),
            Self::Pipe => "pipe".to_string(),
            Self::Sctp => "sctp".to_string(),
            Self::Fc => "fc".to_string(),
            Self::RsvpE2eIgnore => "rsvpe2eignore".to_string(),
            Self::MobilityHeader => "mobilityheader".to_string(),
            Self::UdpLite => "udplite".to_string(),
            Self::Mpls => "mpls".to_string(),
            Self::Manet => "manet".to_string(),
            Self::Hip => "hip".to_string(),
            Self::Shim6 => "shim6".to_string(),
            Self::Wesp => "wesp".to_string(),
            Self::Rohc => "rohc".to_string(),
            Self::EthernetInIpv4 => "ethernetinipv4".to_string(),
            Self::Aggfrag => "aggfrag".to_string(),
            Self::Test1 => "test1".to_string(),
            Self::Test2 => "test2".to_string(),
            Self::Reserved => "reserved".to_string(),
        }
    }
    
    fn to_type(s: String) -> ErrResult<Self> {
        match s.to_lowercase().trim() {
            "hopopt" => Ok(IpProto::HopOpt),
            "icmp" => Ok(IpProto::Icmp),
            "igmp" => Ok(IpProto::Igmp),
            "ggp" => Ok(IpProto::Ggp),
            "ipv4" => Ok(IpProto::Ipv4),
            "stream" => Ok(IpProto::Stream),
            "tcp" => Ok(IpProto::Tcp),
            "cbt" => Ok(IpProto::Cbt),
            "egp" => Ok(IpProto::Egp),
            "igp" => Ok(IpProto::Igp),
            "bbnrccmon" => Ok(IpProto::BbnRccMon),
            "nvpii" => Ok(IpProto::NvpII),
            "pup" => Ok(IpProto::Pup),
            "argus" => Ok(IpProto::Argus),
            "emcon" => Ok(IpProto::Emcon),
            "xnet" => Ok(IpProto::Xnet),
            "chaos" => Ok(IpProto::Chaos),
            "udp" => Ok(IpProto::Udp),
            "mux" => Ok(IpProto::Mux),
            "dcnmeas" => Ok(IpProto::DcnMeas),
            "hmp" => Ok(IpProto::Hmp),
            "prm" => Ok(IpProto::Prm),
            "idp" => Ok(IpProto::Idp),
            "trunk1" => Ok(IpProto::Trunk1),
            "trunk2" => Ok(IpProto::Trunk2),
            "leaf1" => Ok(IpProto::Leaf1),
            "leaf2" => Ok(IpProto::Leaf2),
            "rdp" => Ok(IpProto::Rdp),
            "irtp" => Ok(IpProto::Irtp),
            "tp4" => Ok(IpProto::Tp4),
            "netblt" => Ok(IpProto::Netblt),
            "mfensp" => Ok(IpProto::MfeNsp),
            "meritinp" => Ok(IpProto::MeritInp),
            "dccp" => Ok(IpProto::Dccp),
            "thirdpartyconnect" => Ok(IpProto::ThirdPartyConnect),
            "idpr" => Ok(IpProto::Idpr),
            "xtp" => Ok(IpProto::Xtp),
            "ddp" => Ok(IpProto::Ddp),
            "idprcmtp" => Ok(IpProto::IdprCmtp),
            "tpplusplus" => Ok(IpProto::TpPlusPlus),
            "il" => Ok(IpProto::Il),
            "ipv6" => Ok(IpProto::Ipv6),
            "sdrp" => Ok(IpProto::Sdrp),
            "ipv6route" => Ok(IpProto::Ipv6Route),
            "ipv6frag" => Ok(IpProto::Ipv6Frag),
            "idrp" => Ok(IpProto::Idrp),
            "rsvp" => Ok(IpProto::Rsvp),
            "gre" => Ok(IpProto::Gre),
            "dsr" => Ok(IpProto::Dsr),
            "bna" => Ok(IpProto::Bna),
            "esp" => Ok(IpProto::Esp),
            "ah" => Ok(IpProto::Ah),
            "inlsp" => Ok(IpProto::Inlsp),
            "swipe" => Ok(IpProto::Swipe),
            "narp" => Ok(IpProto::Narp),
            "mobile" => Ok(IpProto::Mobile),
            "tlsp" => Ok(IpProto::Tlsp),
            "skip" => Ok(IpProto::Skip),
            "ipv6icmp" => Ok(IpProto::Ipv6Icmp),
            "ipv6nonxt" => Ok(IpProto::Ipv6NoNxt),
            "ipv6opts" => Ok(IpProto::Ipv6Opts),
            "anyhostinternal" => Ok(IpProto::AnyHostInternal),
            "cftp" => Ok(IpProto::Cftp),
            "anylocalnetwork" => Ok(IpProto::AnyLocalNetwork),
            "satexpak" => Ok(IpProto::SatExpak),
            "kryptolan" => Ok(IpProto::Kryptolan),
            "rvd" => Ok(IpProto::Rvd),
            "ippc" => Ok(IpProto::Ippc),
            "anydistributedfilesystem" => Ok(IpProto::AnyDistributedFileSystem),
            "satmon" => Ok(IpProto::SatMon),
            "visa" => Ok(IpProto::Visa),
            "ipcv" => Ok(IpProto::Ipcv),
            "cpnx" => Ok(IpProto::Cpnx),
            "cphb" => Ok(IpProto::Cphb),
            "wsn" => Ok(IpProto::Wsn),
            "pvp" => Ok(IpProto::Pvp),
            "brsatmon" => Ok(IpProto::BrSatMon),
            "sunnd" => Ok(IpProto::SunNd),
            "wbmon" => Ok(IpProto::WbMon),
            "wbexpak" => Ok(IpProto::WbExpak),
            "isoip" => Ok(IpProto::IsoIp),
            "vmtp" => Ok(IpProto::Vmtp),
            "securevmtp" => Ok(IpProto::SecureVmtp),
            "vines" => Ok(IpProto::Vines),
            "ttp" => Ok(IpProto::Ttp),
            "nsfnetigp" => Ok(IpProto::NsfnetIgp),
            "dgp" => Ok(IpProto::Dgp),
            "tcf" => Ok(IpProto::Tcf),
            "eigrp" => Ok(IpProto::Eigrp),
            "ospfigp" => Ok(IpProto::Ospfigp),
            "spriterpc" => Ok(IpProto::SpriteRpc),
            "larp" => Ok(IpProto::Larp),
            "mtp" => Ok(IpProto::Mtp),
            "ax25" => Ok(IpProto::Ax25),
            "ipip" => Ok(IpProto::Ipip),
            "micp" => Ok(IpProto::Micp),
            "sccsp" => Ok(IpProto::SccSp),
            "etherip" => Ok(IpProto::Etherip),
            "encap" => Ok(IpProto::Encap),
            "anyprivateencryptionscheme" => Ok(IpProto::AnyPrivateEncryptionScheme),
            "gmtp" => Ok(IpProto::Gmtp),
            "ifmp" => Ok(IpProto::Ifmp),
            "pnni" => Ok(IpProto::Pnni),
            "pim" => Ok(IpProto::Pim),
            "aris" => Ok(IpProto::Aris),
            "scps" => Ok(IpProto::Scps),
            "qnx" => Ok(IpProto::Qnx),
            "activenetworks" => Ok(IpProto::ActiveNetworks),
            "ipcomp" => Ok(IpProto::IpComp),
            "snp" => Ok(IpProto::Snp),
            "compaqpeer" => Ok(IpProto::CompaqPeer),
            "ipxinip" => Ok(IpProto::IpxInIp),
            "vrrp" => Ok(IpProto::Vrrp),
            "pgm" => Ok(IpProto::Pgm),
            "anyzerohopprotocol" => Ok(IpProto::AnyZeroHopProtocol),
            "l2tp" => Ok(IpProto::L2tp),
            "ddx" => Ok(IpProto::Ddx),
            "iatp" => Ok(IpProto::Iatp),
            "stp" => Ok(IpProto::Stp),
            "srp" => Ok(IpProto::Srp),
            "uti" => Ok(IpProto::Uti),
            "smp" => Ok(IpProto::Smp),
            "sm" => Ok(IpProto::Sm),
            "ptp" => Ok(IpProto::Ptp),
            "isisoveripv4" => Ok(IpProto::IsisOverIpv4),
            "fire" => Ok(IpProto::Fire),
            "crtp" => Ok(IpProto::Crtp),
            "crudp" => Ok(IpProto::Crudp),
            "sscopmce" => Ok(IpProto::Sscopmce),
            "iplt" => Ok(IpProto::Iplt),
            "sps" => Ok(IpProto::Sps),
            "pipe" => Ok(IpProto::Pipe),
            "sctp" => Ok(IpProto::Sctp),
            "fc" => Ok(IpProto::Fc),
            "rsvpe2eignore" => Ok(IpProto::RsvpE2eIgnore),
            "mobilityheader" => Ok(IpProto::MobilityHeader),
            "udplite" => Ok(IpProto::UdpLite),
            "mpls" => Ok(IpProto::Mpls),
            "manet" => Ok(IpProto::Manet),
            "hip" => Ok(IpProto::Hip),
            "shim6" => Ok(IpProto::Shim6),
            "wesp" => Ok(IpProto::Wesp),
            "rohc" => Ok(IpProto::Rohc),
            "ethernetinipv4" => Ok(IpProto::EthernetInIpv4),
            "aggfrag" => Ok(IpProto::Aggfrag),
            "test1" => Ok(IpProto::Test1),
            "test2" => Ok(IpProto::Test2),
            "reserved" => Ok(IpProto::Reserved),
            _ => Err(VanguardError::Io("unknown ip protocol").into()),
        }
    }
}

impl Parse for XdpRuleAction {
    fn as_str(&self) -> String {
        match self {
            Self::ABORTED => "abort".to_string(),
            Self::DROP => "drop".to_string(),
            Self::PASS => "pass".to_string(),
            Self::TX => "tx".to_string(),
            Self::REDIRECT => "redirect".to_string(),
        }
    }

    fn to_type(s: String) -> ErrResult<Self> {
        match s.to_lowercase().trim() {
            "abort" => Ok(Self::ABORTED),
            "drop" => Ok(Self::DROP),
            "pass" => Ok(Self::PASS),
            "tx" => Ok(Self::TX),
            "redirect" => Ok(Self::REDIRECT),
            _ => Err(VanguardError::Io("unknown action").into())
        }
    }
}