[package]
name = "vanguard-core"
version.workspace = true
edition.workspace = true

[dependencies]
aya = { workspace = true, optional = true }
clap = { workspace = true, features = ["derive"], optional = true }
serde = { workspace = true, features = ["derive"], optional = true }
serde_yaml = { workspace = true }
network-types = { workspace = true }
erret-macro = { workspace = true }
erret-result = { workspace = true }
brevno = { workspace = true }

tokio = { workspace = true }
tonic = { workspace = true }
tonic-prost = { workspace = true }
prost = { workspace = true }

[build-dependencies]
tonic-prost-build = "0.14.6"

[features]
default = ["userspace"]
userspace = ["dep:aya", "dep:clap", "dep:serde"]