[package]
name = "vanguard-daemon"
version.workspace = true
edition.workspace = true

[dependencies]
aya = { workspace = true }
aya-log = { workspace = true }
env_logger = { workspace = true }
tokio = { workspace = true, features = ["full"] }
libsystemd = { workspace = true }
libc = { workspace = true }
vanguard-common = { path = "../vanguard-common" }
vanguard-grpc = { path = "../vanguard-grpc" }

[build-dependencies]
tonic-prost-build = "0.14.6"

[features]
default = []