[package]
name = "vanguard-daemon"
version.workspace = true
edition.workspace = true

[dependencies]
aya = { workspace = true }
aya-log = { workspace = true }
env_logger = { workspace = true }
tokio = { workspace = true, features = ["full"] }
libsystemd = { workspace = true }
vanguard-core = { path = "../vanguard-core" }
vanguard-grpc = { path = "../vanguard-grpc" }
vanguard-config = { path = "../vanguard-config" }

[features]
default = []